In [1]:
import pandas as pd


In [2]:
daily_engagement = pd.read_csv('daily_engagement.csv')

In [3]:
print(len(daily_engagement))

136240


In [4]:
print(daily_engagement['acct'].unique())

[   0    1    2 ... 1302 1303 1305]


In [5]:
import numpy as np

# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

# Change False to True for each block of code to see what it does

# Accessing elements
if True:
    print (countries[0])
    print (countries[3])

# Slicing
if True:
    print (countries[0:3])
    print (countries[:3])
    print (countries[17:])
    print (countries[:])

# Element types
if True:
    print( countries.dtype)
    print (employment.dtype)
    print (np.array([0, 1, 2, 3]).dtype)
    print (np.array([1.0, 1.5, 2.0, 2.5]).dtype)
    print (np.array([True, False, True]).dtype)
    print (np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype)

# Looping
if True:
    for country in countries:
        print ('Examining country {}'.format(country))

    for i in range(len(countries)):
        country = countries[i]
        country_employment = employment[i]
        print ('Country {} has employment {}'.format(country,country_employment))

# Numpy functions
if True:
    print (employment.mean())
    print (employment.std())
    print (employment.max())
    print (employment.sum())

def max_employment(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    max_country = None      # Replace this with your code
    max_value = None   # Replace this with your code

    return (max_country, max_value)

Afghanistan
Angola
['Afghanistan' 'Albania' 'Algeria']
['Afghanistan' 'Albania' 'Algeria']
['Bhutan' 'Bolivia' 'Bosnia and Herzegovina']
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']
<U22
float64
int32
float64
bool
<U2
Examining country Afghanistan
Examining country Albania
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Examining country Bhutan
Examining country Bolivia
Examining country Bosnia and Herzegovina
Country Afghanistan has employment 55.70000076
Count

In [6]:
def max_employment(countries, employment):
    max_country = None
    max_employment = 0
    
    for i in range(len(countries)):
        country = countries[i]
        country_employment = employment[i]
        
        if country_employment > max_employment:
            max_employment = country_employment
            max_country = country
    return(max_country, max_employment)
        

In [7]:
#using numpy

def max_employment2(countries, employment):
    i = employment.argmax()
    return(countries[i],employment[i])

In [8]:
import numpy as np

In [9]:
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

print(countries[0])

Afghanistan


In [10]:
print(countries[:])

['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']


In [11]:
for cn in countries:
    print(f"Examinig country: {cn}")

Examinig country: Afghanistan
Examinig country: Albania
Examinig country: Algeria
Examinig country: Angola
Examinig country: Argentina
Examinig country: Armenia
Examinig country: Australia
Examinig country: Austria
Examinig country: Azerbaijan
Examinig country: Bahamas
Examinig country: Bahrain
Examinig country: Bangladesh
Examinig country: Barbados
Examinig country: Belarus
Examinig country: Belgium
Examinig country: Belize
Examinig country: Benin
Examinig country: Bhutan
Examinig country: Bolivia
Examinig country: Bosnia and Herzegovina


In [12]:
print(employment.max())

75.69999695


In [13]:
v1 = np.array([1,2,3])

v2 = np.array([4,5,6])
print(v1+v2)

[5 7 9]


In [14]:
print(v1 * 3)

[3 6 9]


In [15]:
a = np.array([1,2,3,4])
b = np.array([1,2,1,2])

In [16]:
if True:
    print(a ** b)

[ 1  4  3 16]


In [17]:
if True:
    b = 2
    print(a + b)
    print(a ** b)

[3 4 5 6]
[ 1  4  9 16]


In [18]:
if True:
    a = np.array([True, True, False,False])
    b=  np.array([True, False, True, False])
    
    print(a & b)
    print(a | b)
    print(~a)
    

[ True False False False]
[ True  True  True False]
[False False  True  True]


In [19]:
if True:
    a = np.array([1,2,3,4])
    b = 2
    
    print(a > b)

[False False  True  True]


In [20]:
countries = np.array([
       'Algeria', 'Argentina', 'Armenia', 'Aruba', 'Austria','Azerbaijan',
       'Bahamas', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Bolivia',
       'Botswana', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Cape Verde'
])
# Female school completion rate in 2007 for those 20 countries
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])


In [21]:
def overall_completion_rate(female_completion, male_completion):
    total_array = np.array(female_completion + male_completion)
    return (total_array/2.)


In [22]:
# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])


In [23]:
country_name = 'United States'

In [24]:
def standardize_data(values):
    '''
    Fill in this function to return a standardized version of the given values,
    which will be in a NumPy array. Each value should be translated into the
    number of standard deviations that value is away from the mean of the data.
    (A positive number indicates a value higher than the mean, and a negative
    number indicates a value lower than the mean.)
    '''
    stan_values = (values - values.mean()) / values.std()
    return stan_values

## Numpy Index Array

In [25]:
# Using index arrays
if True:
    a = np.array([1, 2, 3, 4])
    b = np.array([True, True, False, False])
    
    print(a[b])
    print(a[np.array([True, False, True, False])])


[1 2]
[1 3]


In [26]:
# Creating the index array using vectorized operations
if True:
    a = np.array([1, 2, 3, 2, 1])
    b = (a >= 2)
    print(a[b])

    print(a[a>=2])

[2 3 2]
[2 3 2]


In [27]:
# Creating the index array using vectorized operations on another array
if True:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([1, 2, 3, 2, 1])
    
    print(b==2)
    print(a[b==2])


[False  True False  True False]
[2 4]


In [28]:
# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])


In [29]:
def mean_time_for_paid_students(time_spent, days_to_cancel):
    '''
    Fill in this function to calculate the mean time spent in the classroom
    for students who stayed enrolled at least (greater than or equal to) 7 days.
    Unlike in Lesson 1, you can assume that days_to_cancel will contain only
    integers (there are no students who have not canceled yet).
    
    The arguments are NumPy arrays. time_spent contains the amount of time spent
    in the classroom for each student, and days_to_cancel contains the number
    of days until each student cancel. The data is given in the same order
    in both arrays.
    '''
    time_spent = time_spent[days_to_cancel >= 7]
    
    return (time_spent.mean())


### + vs +=

In [30]:
a = np.array([1,2,3,4])
b = a

a +=np.array([1,1,1,1])
print(b)

[2 3 4 5]


In [31]:
a = np.array([1,2,3,4])
b = a
a = a + np.array([1,1,1,1])

print(b)

[1 2 3 4]


## in-place vs. not in-place
### += operate in-place while + does not

In [32]:
a = np.array([1,2,3,4,5])
slice = a[:3]
slice[0] = 100
print(a)

[100   2   3   4   5]


# Pandas Series

In [33]:
import pandas as pd

countries = ['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
             'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
             'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia']

life_expectancy_values = [74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6]

gdp_values = [ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981]

In [34]:
life_expentancy = pd.Series(life_expectancy_values)
gdp = pd.Series(gdp_values)

In [35]:
print(life_expentancy.describe())

count    20.000000
mean     72.870000
std       6.213999
min      57.600000
25%      70.175000
50%      73.450000
75%      75.650000
max      83.400000
dtype: float64


In [36]:
if True:
        print(life_expentancy[0])
        print(gdp[3:7])

74.7
3      562.987685
4    13495.127466
5     9388.688523
6     1424.190562
dtype: float64


In [37]:
#looping 
if True:
    for cle in life_expentancy:
        print(f"Examining life expectancy {cle}")

Examining life expectancy 74.7
Examining life expectancy 75.0
Examining life expectancy 83.4
Examining life expectancy 57.6
Examining life expectancy 74.6
Examining life expectancy 75.4
Examining life expectancy 72.3
Examining life expectancy 81.5
Examining life expectancy 80.2
Examining life expectancy 70.3
Examining life expectancy 72.1
Examining life expectancy 76.4
Examining life expectancy 68.1
Examining life expectancy 75.2
Examining life expectancy 69.8
Examining life expectancy 79.4
Examining life expectancy 70.8
Examining life expectancy 62.7
Examining life expectancy 67.3
Examining life expectancy 70.6


In [38]:
## PANDAS Functions

if True:
    print(life_expentancy.mean())
    print(life_expentancy.std())
    print(gdp.max())
    print(gdp.min())

72.86999999999999
6.213999474869968
27036.48733192
366.04496652


In [39]:
## vectorize opeations

if True:
    a = pd.Series([1,2,3,4])
    b = pd.Series([1,2,1,2])

    print( a+b)
    print(a*b)
    print(a >= 3)
    print(a[a>=3])

0    2
1    4
2    4
3    6
dtype: int64
0    1
1    4
2    3
3    8
dtype: int64
0    False
1    False
2     True
3     True
dtype: bool
2    3
3    4
dtype: int64


In [40]:
a = pd.Series([1,2,3,4])
print(a.mean())

2.5


In [41]:
   
def variable_correlation(variable1, variable2):
    '''
    Fill in this function to calculate the number of data points for which
    the directions of variable1 and variable2 relative to the mean are the
    same, and the number of data points for which they are different.
    Direction here means whether each value is above or below its mean.
    
    You can classify cases where the value is equal to the mean for one or
    both variables however you like.
    
    Each argument will be a Pandas series.
    
    For example, if the inputs were pd.Series([1, 2, 3, 4]) and
    pd.Series([4, 5, 6, 7]), then the output would be (4, 0).
    This is because 1 and 4 are both below their means, 2 and 5 are both
    below, 3 and 6 are both above, and 4 and 7 are both above.
    
    On the other hand, if the inputs were pd.Series([1, 2, 3, 4]) and
    pd.Series([7, 6, 5, 4]), then the output would be (0, 4).
    This is because 1 is below its mean but 7 is above its mean, and
    so on.
    '''
    both_above = (variable1 > variable1.mean()) & (variable2 > variable2.mean())
    both_below = (variable1 < variable1.mean()) & (variable2 < variable2.mean())
    
    is_same_direction = both_above | both_below        # Replace this with your code
    num_same_direction = is_same_direction.sum()
    num_different_direction = len(variable1) - num_same_direction # Replace this with your code
    
    return (num_same_direction, num_different_direction)

In [42]:
var1 = pd.Series([1, 2, 3, 4])
var2 = pd.Series([10, 11, 12, 13])
print(variable_correlation(var1, var2))

(4, 0)


In [43]:
# Numpy arrays are like souped-up Python Lists
# A Pandas series is like a cross between a list and a dictionary


In [44]:

countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola',
    'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
    'Barbados', 'Belarus', 'Belgium', 'Belize',
    'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
]


employment_values = [
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076,
]


In [49]:
employment = pd.Series(employment_values, index = countries)

print(employment.max())
print(employment.idxmax())

def max_employment(employment):
    max_country = employment.idxmax()
    max_value = employment.max()

75.69999695
Angola


## Vectorize operations and Series Indexex

In [51]:
# Addition when indexes are the same
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
    print (s1 + s2)


a    11
b    22
c    33
d    44
dtype: int64


In [52]:
# Indexes have same elements in a different order
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['b', 'd', 'a', 'c'])
    print (s1 + s2)


a    31
b    12
c    43
d    24
dtype: int64


In [54]:
# Indexes overlap, but do not have exactly the same elements
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])
    print (s1 + s2)


a     NaN
b     NaN
c    13.0
d    24.0
e     NaN
f     NaN
dtype: float64


In [56]:
# Indexes do not overlap
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['e', 'f', 'g', 'h'])
    print (s1 + s2)

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64


In [58]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])

sum1 = s1+s2
print(sum1)
print(sum1.dropna())

a     NaN
b     NaN
c    13.0
d    24.0
e     NaN
f     NaN
dtype: float64
c    13.0
d    24.0
dtype: float64


In [59]:
# Try to write code that will add the 2 previous series together,
# but treating missing values from either series as 0. The result
# when printed out should be similar to the following line:
# print pd.Series([1, 2, 13, 24, 30, 40], index=['a', 'b', 'c', 'd', 'e', 'f'])

s1.add(s2, fill_value=0)

a     1.0
b     2.0
c    13.0
d    24.0
e    30.0
f    40.0
dtype: float64

In [63]:
def add3(x):
    return x+3

print(s1)
s1.apply(add3)

a    1
b    2
c    3
d    4
dtype: int64


a    4
b    5
c    6
d    7
dtype: int64

In [64]:
states = pd.Series([
    'california',
    'oh',
    'michigan',
    'ny'
])

In [75]:
def cleaning_states(state):
    if len(state) == 2:
        return state
    elif state == 'california':
        return "ca"
    elif state == 'michigan':
        return "mi"

In [76]:
clean_states = []
for state in states:
    clean_states.append(cleaning_states(state))
clean_states = pd.Series(clean_states)

In [77]:
print(clean_states)

0    ca
1    oh
2    mi
3    ny
dtype: object


In [80]:

# Example pandas apply() usage (although this could have been done
# without apply() using vectorized operations)
if True:
    s = pd.Series([1, 2, 3, 4, 5])
    def add_one(x):
        return x + 1
    print (s.apply(add_one))


0    2
1    3
2    4
3    5
4    6
dtype: int64


In [81]:

names = pd.Series([
    'Andre Agassi',
    'Barry Bonds',
    'Christopher Columbus',
    'Daniel Defoe',
    'Emilio Estevez',
    'Fred Flintstone',
    'Greta Garbo',
    'Humbert Humbert',
    'Ivan Ilych',
    'James Joyce',
    'Keira Knightley',
    'Lois Lane',
    'Mike Myers',
    'Nick Nolte',
    'Ozzy Osbourne',
    'Pablo Picasso',
    'Quirinus Quirrell',
    'Rachael Ray',
    'Susan Sarandon',
    'Tina Turner',
    'Ugueth Urbina',
    'Vince Vaughn',
    'Woodrow Wilson',
    'Yoji Yamada',
    'Zinedine Zidane'
])


In [104]:
def reverse_name(name):
    split_name = name.split(" ")
    first_name = split_name[0]
    last_name =  split_name[1]
    
    return(last_name + ", " + first_name)

In [105]:
reverse_name(names.iloc[0])

'Agassi, Andre'

In [106]:
def reverse_names(names):
    return names.apply(reverse_name)

In [107]:
reverse_names(names)

0             Agassi, Andre
1              Bonds, Barry
2     Columbus, Christopher
3             Defoe, Daniel
4           Estevez, Emilio
5          Flintstone, Fred
6              Garbo, Greta
7          Humbert, Humbert
8               Ilych, Ivan
9              Joyce, James
10         Knightley, Keira
11               Lane, Lois
12              Myers, Mike
13              Nolte, Nick
14           Osbourne, Ozzy
15           Picasso, Pablo
16       Quirrell, Quirinus
17             Ray, Rachael
18          Sarandon, Susan
19             Turner, Tina
20           Urbina, Ugueth
21            Vaughn, Vince
22          Wilson, Woodrow
23             Yamada, Yoji
24         Zidane, Zinedine
dtype: object

In [108]:
import pandas as pd
import seaborn as sns


In [ ]:
employment = pd.read_csv('employment_above_15.csv', index_col='Country')
female_completion = pd.read_csv('female_completion_rate.csv', index_col='Country')
male_completion = pd.read_csv('male_completion_rate.csv', index_col='Country')
life_expectancy = pd.read_csv('life_expectancy.csv', index_col='Country')
gdp = pd.read_csv('gdp_per_capita.csv', index_col='Country')
