In [5]:
import re
import numpy as np
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)


['bat', 'bot']


In [6]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result

NameError: name 'a' is not defined

In [12]:
s = (20,20)
a = np.ones(s)
b = np.ones(s)

In [14]:
l2_dist(a.T,b.T)

0.0

In [18]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [19]:
print(a1,a2,a3,a4,a5)

[0.03679212 0.29031351 0.89389141 0.08970332] [[0.4594966 ]
 [0.88026665]
 [0.62121442]
 [0.43601018]] [[1 2 3 4]] [1 2 3] [1. 2. 3. 4.]


In [22]:
a1.shape==a2.shape

False

In [23]:
a4.ndim == 1

True

In [24]:
4

4

In [25]:
a4

array([1, 2, 3])

In [26]:
old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [27]:
s = (6,6)
a = np.ones(s)
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
b = np.array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 14., 15., 1., 1.],
       [1., 1., 14., 15., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])


In [39]:
b[2:4, 2:4]

array([[14., 15.],
       [14., 15.]])

In [40]:
import re
s = 'ACBCAC'

In [46]:
re.findall('AC',s)

['AC', 'AC']

In [47]:
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(L)

5


In [48]:
s = '''Office of Research Administration: (734) 647-6333 | 4325 North Quad
Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
Office of the Dean: (734) 647-3576 | 4322 North Quad
UMSI Engagement Center: (734) 763-1251 | 777 North University
Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad'''

In [49]:
print(s)

Office of Research Administration: (734) 647-6333 | 4325 North Quad
Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
Office of the Dean: (734) 647-3576 | 4322 North Quad
UMSI Engagement Center: (734) 763-1251 | 777 North University
Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad


In [55]:
re.findall('\d{3}[-]\d{3}[-]\d{4}',s)

[]

In [56]:
re.findall('\d{3}\s\d{3}[-]\d{4}',s)

[]

In [58]:
re.findall('[(]\d{3}[)]\s\d{3}[-]\d{4}',s)

['(734) 647-6333',
 '(734) 647-8044',
 '(734) 763-2285',
 '(734) 647-3576',
 '(734) 763-1251',
 '(734) 764-9376']

In [59]:
text = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'

In [72]:
re.findall('(?P<=https:\/\/)([.]*)',text)
#re.findall('(?P<=https:\/\/)([A-Za-z0-9.])*',text)
#re.findall('(?P<=[https]:\/\/)([A-Za-z0-9.])*',text)
#re.findall('(?<=https:\/\/)([A-Za-z0-9])*',text)

error: missing >, unterminated name at position 4

In [76]:
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''


In [78]:
pattern = 'freedom'
print(len(re.findall(pattern,text)))

6
